version: '3.3'
services:
  webshark:
    container_name: WebShark 
    #build: ./
    image: webshark:latest 
    stdin_open: true
    tty: true
    volumes:
      - ./pcaps:/caps:ro
    expose:
      - 80
    ports:
      - 8000:80
